### ISSUE TITLE
connect_activate with mutable variables

### ISSUE THREAD

**Issue by C-Bouthoorn** [gtk-rs/examples#115]
Using a mutable variable in a `connect_activate` closure gives an error: ```cannot borrow captured outer variable in an `Fn` closure as mutable```

Example code:
```
let item = MenuItem::new_with_label("Add one");

struct Variable {
    pub value: u32
}

let mut x = Variable {
    value: 0
};

impl Variable {
    pub fn add(&mut self, x: u32) {
        self.value += x;
    }
}

item.connect_activate(move |_| {
    x.add(10);
});
```

**Comment by GuillaumeGomez** [comment]
`Rc<RefCell<YourVariable>>`

**Comment by C-Bouthoorn** [comment]
```
item.connect_activate(move |_| {
    Rc< RefCell<x> >.add(10);
});
```

in that example gives `chained comparison operators require parentheses` and ```expected expression, found `>` ```

**Comment by GuillaumeGomez** [comment]
O.O

**Comment by GuillaumeGomez** [comment]
Do you even rust?

**Comment by GuillaumeGomez** [comment]
So, going from basics. Copy/paste this [macro](https://github.com/gtk-rs/examples/blob/721b8966379bc61e28473c0383e2a29c01c317c6/src/gtktest.rs#L17-L32) into your code. Then use it as [follow](https://github.com/gtk-rs/examples/blob/721b8966379bc61e28473c0383e2a29c01c317c6/src/gtktest.rs#L89-L98).

**Comment by C-Bouthoorn** [comment]
```
item.connect_activate(move |_| {
    Rc< RefCell<x> >.add(10);
});
```

in that example gives `chained comparison operators require parentheses` and ```expected expression, found `>` ```

**Comment by C-Bouthoorn** [comment]
I just started out with Rust, yeah, but thanks for the help anyhow. It seems to work

**Comment by GuillaumeGomez** [comment]
No problem, it just caught me completely off guards. Hope it helped!

**Comment by C-Bouthoorn** [comment]
I'm sorry for saying it; but it still doesn't work.

```
    let item = MenuItem::new_with_label("Add one");

    #[derive(Clone)]
    struct Variable {
        pub value: u32
    }

    let mut x = Variable {
        value: 0
    };

    impl Variable {
        pub fn add(&mut self, x: u32) {
            self.value += x;
        }
    }

    item.connect_activate(clone!(x => move |_| {
        x.add(10);
    }));
```

The macro is at the top of the file.

Yet I keep getting the same error. I'm not sure what I'm doing wrong...

**Comment by GuillaumeGomez** [comment]
You still don't use `Rc<Refcell<T>>`. Try this:

```rust
let item = MenuItem::new_with_label("Add one");

#[derive(Clone)]
struct Variable {
    pub value: u32
}

let mut x = Rc::new(RefCell::new(Variable {
    value: 0
}));

impl Variable {
    pub fn add(&mut self, x: u32) {
        self.value += x;
    }
}

item.connect_activate(clone!(x => move |_| {
    x.borrow_mut().add(10);
}));
```

**Comment by C-Bouthoorn** [comment]
Nice, now it does work :smile:  thanks again
