### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by sinitcin** [gtk-rs/examples#130]
> Build failed, waiting for other jobs to finish...
> error: linking with `gcc` failed: exit code: 1
>   |
>   = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\r
> ustlib\\x86_64-pc-windows-gnu\\lib\\crt2.o" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Program Fi
> les\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "D:\\examples\\target\\debug\\deps\\multithreading_context-16409705b3c5ece5.0.o" "-o" "D:\
> \examples\\target\\debug\\deps\\multithreading_context-16409705b3c5ece5.exe" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "D:\\examples\\target\\debug\\deps" "-L"
>  "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "D:\\examples\\target\\debug\\deps\\libgtk-
> b75070d394db431b.rlib" "D:\\examples\\target\\debug\\deps\\libgtk_sys-d6a702c36b9163af.rlib" "D:\\examples\\target\\debug\\deps\\libgio-3f9c7f1b95d63cae.rlib"
> "D:\\examples\\target\\debug\\deps\\libpango-5dff3ce5d9479dad.rlib" "D:\\examples\\target\\debug\\deps\\libatk_sys-4c92419d575bce35.rlib" "D:\\examples\\target
> \\debug\\deps\\libgdk-01d71676dd62d208.rlib" "D:\\examples\\target\\debug\\deps\\libcairo-797883c772650ade.rlib" "D:\\examples\\target\\debug\\deps\\libgdk_pix
> buf-11e9df44bfa4bcd2.rlib" "D:\\examples\\target\\debug\\deps\\libglib-fea96c909af070b7.rlib" "D:\\examples\\target\\debug\\deps\\libbitflags-8510a47beebe00a6.
> rlib" "D:\\examples\\target\\debug\\deps\\libgdk_sys-77693c795ea1765f.rlib" "D:\\examples\\target\\debug\\deps\\libcairo_sys-97f77cde66cc6e14.rlib" "D:\\exampl
> es\\target\\debug\\deps\\libwinapi-a5898d7aceb63fac.rlib" "D:\\examples\\target\\debug\\deps\\libpango_sys-f40c5761e34216c0.rlib" "D:\\examples\\target\\debug\
> \deps\\libgdk_pixbuf_sys-e605de4e90e7ae24.rlib" "D:\\examples\\target\\debug\\deps\\libgio_sys-057d4bc21ac4b427.rlib" "D:\\examples\\target\\debug\\deps\\libgo
> bject_sys-4ba000a4d9f2cf78.rlib" "D:\\examples\\target\\debug\\deps\\libglib_sys-895440df8bd9794c.rlib" "D:\\examples\\target\\debug\\deps\\libbitflags-6c0c42f
> 1f858d67c.rlib" "D:\\examples\\target\\debug\\deps\\liblibc-5dc7b85e748840b4.rlib" "D:\\examples\\target\\debug\\deps\\libc_vec-3ad5b18b850a7482.rlib" "C:\\Pro
> gram Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-2534c0bd05ee265e.rlib" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustli
> b\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-e3cf511e7374526b.rlib" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libun
> wind-52e8ab7efa40b1b3.rlib" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-96a4c6f6006d0a44.rlib" "C:\\Program Fil
> es\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librand-32b552aabc8b4e3c.rlib" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_
> 64-pc-windows-gnu\\lib\\libcollections-4965c4d8d37432ab.rlib" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-8bdc
> 91ebec92bb48.rlib" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc_system-1769b774bd375392.rlib" "C:\\Program File
> s\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_unicode-feba27dd5784a3dc.rlib" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib
> \\x86_64-pc-windows-gnu\\lib\\libcore-d1dd5a39fb635c62.rlib" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_bu
> iltins-35b663261c982c37.rlib" "-l" "gtk-3" "-l" "gdk-3" "-l" "atk-1.0" "-l" "gdk-3" "-l" "cairo" "-l" "pango-1.0" "-l" "gdk_pixbuf-2.0" "-l" "gio-2.0" "-l" "go
> bject-2.0" "-l" "glib-2.0" "-l" "gobject-2.0" "-l" "advapi32" "-l" "ws2_32" "-l" "userenv" "-l" "shell32" "-l" "gcc_eh" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvc
> rt" "-luser32" "-lkernel32" "C:\\Program Files\\Rust stable GNU 1.16\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
>   = note: ld: cannot find -lgtk-3
>           ld: cannot find -lgdk-3
>           ld: cannot find -latk-1.0
>           ld: cannot find -lgdk-3
>           ld: cannot find -lcairo
>           ld: cannot find -lpango-1.0
>           ld: cannot find -lgdk_pixbuf-2.0
>           ld: cannot find -lgio-2.0
>           ld: cannot find -lgobject-2.0
>           ld: cannot find -lglib-2.0
>           ld: cannot find -lgobject-2.0
> 
> 
> error: aborting due to previous error
> 
> error: build failed
>

**Comment by sinitcin** [comment]
Please help me to run "cargo build" without error =(

**Comment by EPashkin** [comment]
You follow http://gtk-rs.org/docs-src/requirements.html ?

**Comment by sinitcin** [comment]
Of course 
```
C:\>echo %PATH%
C:\msys2\mingw64\bin;C:\Program Files\Rust stable GNU 1.16\bin; ...
```
and 
```
C:\>echo %GTK_LIB_DIR%
C:\msys2\mingw64\lib
```

**Comment by sinitcin** [comment]
А чёйта мы на английском? =)

**Comment by sinitcin** [comment]
В общем, решение нашёл. Грубо. Просто копирую содержимое 
`C:\msys64\mingw64\lib`
в => 
`C:\Program Files\Rust stable GNU 1.16\lib\rustlib\x86_64-pc-windows-gnu\lib`

и всё собирается... Вероятно, как-то для cargo нужно прописать дополнительные пути, чтобы он видел библиотеки в msys, но не знаю какие =\
