### ISSUE TITLE
Move examples over to gtk::Application

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/examples#140]
... which is the new, modern way of doing GTK applications.

**Comment by GuillaumeGomez** [comment]
Hum, still not done? Damn. I'll try to do it when I have time.

**Comment by sdroege** [comment]
@GuillaumeGomez This is done now, right?

**Comment by GuillaumeGomez** [comment]
Indeed, thanks for the reminder!

**Comment by russel** [comment]
Is it wise to close this issue before the activity is complete?

**Comment by GuillaumeGomez** [comment]
It's been done since a few weeks now. What activity are you referring to?

**Comment by russel** [comment]
I thought all the example of using gtk-rs were going to move from explicit init() and main() calls to using an gtk::Application. This hasn't happened for https://github.com/gtk-rs/examples/blob/master/src/bin/builder_basics.rs for example.

**Comment by GuillaumeGomez** [comment]
You're not looking at the correct branch. Take a look at the examples in pending. ;)

**Comment by russel** [comment]
If it isn't in master it isn't finished yet. :-)

But yes looking much nicer. Thanks.
