### ISSUE TITLE
Check for and fix all reference cycles in closures

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/examples#179]
One very direct example is here: https://github.com/gtk-rs/examples/blob/30549d056f21eafba755f8084f3cb8a85e4f6736/src/bin/clock.rs#L46-L49

The window will never be destroyed here because it keeps another strong reference to itself via the closure. Here this is completely unneeded even, the first parameter to the closure would already be the window.

In other cases we should use weak references instead if the data is not available from somewhere else.

----

The same problem can also happen in other places with `Arc`/`Rc`, and also indirectly between `GObject`s and those types. We should check all closures if they directly or indirectly (A has a reference to B, B has a reference to C, C has a reference to A) creates a reference cycle.

Checking all calls to `clone()` and usages of the `clone!` macro would be a good start.

**Comment by sdroege** [comment]
Most are fixed now but e.g. all usages of the `clone!` macro in gtktest are wrong still. Probably in some other examples too

**Comment by GuillaumeGomez** [comment]
This is worth a new PR I guess! ;)
