### ISSUE TITLE
could not compile due to LINK error

### ISSUE THREAD

**Issue by coolit** [gtk-rs/examples#190]
I used rustc 1.28.0 in IDEA on WIN1064x machine, and could compile other projects. But not lucky with gtk-rs. 
-----------------------------
error: linking with `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX64\x64\link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\Administrator\\Desktop\\gtk\\target\\debug\\deps\\clock-0cbd5ba87e55ec12.10ygozpgsu0ud2lu.rcgu.o" "C:\\Users\\Administrator\\Desktop\\gtk\\target\\debug\\deps\\clock-0cbd5ba87e55ec12.16u6js6g0l3k1ic6.rcgu.o" 
...
...
  = note: Non-UTF-8 output: LINK : fatal error LNK1181: \xce\xde\xb7\xa8\xb4\xf2\xbf\xaa\xca\xe4\xc8\xeb\xce\xc4\xbc\xfe\xa1\xb0gtk-3.lib\xa1\xb1\r\n

error: aborting due to previous error

**Comment by EPashkin** [comment]
Try set GTK_LIB_DIR and PATH environment variables.

**Comment by coolit** [comment]
In cmd, I tried to use the command below, but error was still there.
SETX GTK_LIB_DIR C:\msys64\mingw64\lib
SETX PATH C:\msys64\mingw64\bin

**Comment by coolit** [comment]
I added mingw64/bin to GTK_LIB_DIR, but it didn't work.  So where could I download one MVS version of gtk?

**Comment by EPashkin** [comment]
2.16 https://sourceforge.net/projects/gladewin32/
http://old.grakovne.org/files/GTK/gtk+-bundle_3.6.4-20130921_win32.zip
Or build it yourself https://www.gtk.org/download/index.php
Or use `stable-x86_64-pc-windows-gnu` with msys64, not sure that it works with MVS really

**Comment by coolit** [comment]
After following the requirements as in http://gtk-rs.org/docs/requirements.html, it worked.
