### ISSUE TITLE
Trying on windows

### ISSUE THREAD

**Issue by RCasatta** [gtk-rs/examples#214]
I followed the requirements instrunction so I have 

```
echo %GTK_LIB_DIR% 
C:\msys64\mingw64\lib
echo %PATH%
... C:\msys64\mingw64\bin;
```

and when I launch `cargo build` I got:   
`= note: LINK : fatal error LNK1181: cannot open input file 'gtk-3.lib'`

rustc 1.31.1 (b6c32da9b 2018-12-18)

**Comment by EPashkin** [comment]
File C:\msys64\mingw64\lib\libgtk-3.dll.a present in dir?
What `rustup show` says in your project?
By `note: LINK` I suspect that you use `stable-x86_64-pc-windows-msvc` instead `stable-x86_64-pc-windows-gnu`

**Comment by RCasatta** [comment]
bingo!

yes the file is present, and yes I am using msvc instead of gnu.
using `rustup override add stable-gnu` fixes the problem

thank you
