### ISSUE TITLE
Gtk-rs create liststore for combobox model

### ISSUE THREAD

**Issue by dkoch144** [gtk-rs/examples#239]
I’m trying to write a simple GUI for setting up XML configurations and I’m looking for how to add a liststore model to populate the options of a combobox.

I’ve found the example in this project with a TreeStore as the model for the combobox but that doesn’t seem to be working exactly correctly although it does create the correct number of items in the drop down.

When I do a liststore version, the length of the dropdown changes but there are no items showing in it.

```
let model = ListStore::new(&[String::static_type()]);

    for i in 0..10 {
        // insert_with_values takes two slices: column indices and ToValue
        // trait objects. ToValue is implemented for strings, numeric types,
        // bool and Object descendants
        let iter = model.insert_with_values(None, &[0], &[&format!("Hello {}", i)]);

        for _ in 0..i {
            model.insert_with_values(Some(i), &[0], &[&"I'm a child node"]);
        }
    }

    let combo = ComboBox::new_with_model(&model);
```

I've seen examples using Glade as the source but I want to build it dynamically.

**Comment by EPashkin** [comment]
Try use https://github.com/gtk-rs/examples/blob/master/src/bin/list_store.rs#L203 instead `insert_with_values`

```
store.set(&store.append(), &[0], &[&"I'm a child node"]
```

and I don't see code that actually shows column like https://github.com/gtk-rs/examples/blob/master/src/bin/list_store.rs#L225-L236

**Comment by dkoch144** [comment]
That second reference looks like it's being used to add the store/model columns we want displayed to the treeview. Do I need to use a treeview? I was playing in Glade to get a sense of things and I was able to add a liststore to a combobox as its model without having any treeview mentioned. I think you're right that the column data is being added to the liststore but the parent widget isn't being told to display the data properly, I'm missing that piece, probably just one function I need to locate for a combobox.

This example uses a treeview but no combobox

https://github.com/gtk-rs/examples/blob/master/src/bin/treeview.rs

**Comment by EPashkin** [comment]
https://developer.gnome.org/gtk3/stable/GtkComboBox.html
"The GtkComboBox uses the model-view pattern; the list of valid choices is specified in the form of a tree model, and the display of the choices can be adapted to the data in the model by using cell renderers, as you would in a tree view"
seems you need [add attribute with renderer](https://gtk-rs.org/docs/gtk/trait.CellLayoutExt.html#tymethod.add_attribute) anyway.
Or use https://gtk-rs.org/docs/gtk/struct.ComboBoxText.html instead

**Comment by EPashkin** [comment]
*ComboBox implement CellLayoutExt too.

**Comment by dkoch144** [comment]
Thank you @EPashkin I think I'm just going to use comboboxtext for now. I am also having issues cloning a widget and packing it into a new box as an action triggered by a button click. I'm trying to dynamically build a list of options which can be combined with boolean operators but when I try to pack the cloned combooxtext into a new box that I'm going to add to the window, I get this error

`(.:31706): Gtk-CRITICAL **: 09:05:50.807: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed`

**Comment by EPashkin** [comment]
gtk_box_pack is right, you can't add add one widget to 2 parent,
instead rust cloning (it just add reference to it) you need recreate control
or remove it from old parent

**Comment by dkoch144** [comment]
@EPashkin Thank you for your help! I'm still a bit confused though, I thought that the point of clone being implemented for a struct is to do a deep copy of it, not create a reference. Is this because of how the bindings to the C libraries are working? Do you have any references for how to recreate control? My goal is to just be able to do a deep copy of a gtk widget, can I do this by implementing clone myself?

**Comment by EPashkin** [comment]
In gtk-rs\glib all object is like [`Rc<RefCell<T>>`](https://gtk-rs.org/docs/glib/#objects) and `clone` works same, all clones points to same real glib object.
There no good way do create "deep clone" for glib object even in C (at minimum google don't find it by "gtk duplicate widget").
IMHO you don't need duplicate at all as you can just call function and create new instance with same settings.
