### ISSUE TITLE
Repos in "crate" branch need to use "master" branch of examples

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/examples#285]
Currently it only fixed in glib and gtk

cc @GuillaumeGomez, @sdroege

**Comment by EPashkin** [comment]
Added fixes for gio and gdk.

I will add Atk, pango, pangocairo, sourceview, gdk-pixbuf on weekend

**Comment by GuillaumeGomez** [comment]
I merged two out of the three. I'll let @sdroege handle the gio one. Thanks @EPashkin !

**Comment by EPashkin** [comment]
Seems issue fixed for all crates, so I close this
