### ISSUE TITLE
clutter-gtk rust binding?

### ISSUE THREAD

**Issue by artonio** [gtk-rs/examples#291]
I'm sorry, I don't know where else to ask this. Are there rust binding for [Clutter-gtk](https://github.com/GNOME/clutter-gtk). I really would like to implement drag n drop from clutter to GTK window, anyone know how?

**Comment by GuillaumeGomez** [comment]
I don't know of any myself. Asking through the GNOME channels might give you more results maybe?

**Comment by artonio** [comment]
Thanks, I will try. Unfortunately I don't know C well enough to make the bindings :(

**Comment by GuillaumeGomez** [comment]
If it has gir files, you can use [gir](https://github.com/gtk-rs/gir) to generate most of the library in rust. There even is a tutorial on how to use it [here](https://gtk-rs.org/docs-src/tutorial/gir_tutorial).

**Comment by artonio** [comment]
Hmm, I don't see the gir files in their repo. Any way i can generate gir files from C?

**Comment by EPashkin** [comment]
https://packages.ubuntu.com/eoan/libclutter-gtk-1.0-dev have GtkClutter-1.0.gir
but it depends for https://packages.ubuntu.com/eoan/libclutter-1.0-dev 's gir file,
and it depends for many untranslated libs too.

**Comment by GuillaumeGomez** [comment]
So you might be able to generate everything if all the generation works well, which I strongly doubt. But that'd be interesting for `gir` to get new bug reports.

**Comment by artonio** [comment]
thanks for all the help! i will investigate

**Comment by GuillaumeGomez** [comment]
Closing then. Don't hesitate to comment here what you did in the end. :)
