### ISSUE TITLE
Clone_macros doesn't work 

### ISSUE THREAD

**Issue by swanux** [gtk-rs/examples#293]
I've tried to use this macro (even the example) but it doesn't work. There is no error during compile time, but it does nothing on button click (the example doesn't even open). Does anyone have any idea?

**Comment by GuillaumeGomez** [comment]
If you want help, you need to provide code, we can't guess what's wrong without it.

**Comment by swanux** [comment]
I mean the example which you provided https://github.com/gtk-rs/examples/blob/master/src/bin/clone_macro.rs

**Comment by GuillaumeGomez** [comment]
I can confirm that the clone_macro example is definitely not working... Checking what's going on.

**Comment by swanux** [comment]
Thank you!

**Comment by GuillaumeGomez** [comment]
Ok, understood the problem in the example. It's very stupid... I'll add some debug calls in the clone macro to help users because it's definitely an issue... I'll comment with the PR so you can see what is wrong.

**Comment by GuillaumeGomez** [comment]
You can see #294.

**Comment by swanux** [comment]
Yeah, I see. It really wasn't that complicated. Now my program also works. Thank you very much for the quick help!
