### ISSUE TITLE
How to set app menu bar on macOS?

### ISSUE THREAD

**Issue by kornelski** [gtk-rs/examples#302]
There's a menu bar example, but it creates an in-window menu, which is inappropriate for macOS.

I've found that there's `GtkApplicationExt::set_menubar` that might be setting the native screen-top menu bar, but this method wants `gio::MenuModel`, and I can't find documentation how to create that object in Rust.

**Comment by GuillaumeGomez** [comment]
I'm building a "system" menu bar here: https://github.com/GuillaumeGomez/process-viewer/blob/master/src/process_viewer.rs#L361

**Comment by kornelski** [comment]
Thanks!
