### ISSUE TITLE
How to display TreeView backed by a Vec of Rust objects

### ISSUE THREAD

**Issue by kornelski** [gtk-rs/examples#304]
Examples show how to bind a `ListStore` or `TreeStore` to a `TreeView`, but it seems like this relies on the store being the source of truth for this data, and the data to be stored as separate `Value`s in separate columns.

What I'm missing is how to use Rust-native type as the data source for a `TreeView`, especially if the `TreeView` is sortable.

My data lives in a `Vec<RustStruct>`, and I'd like to display some of the fields of that struct in `TreeView`'s columns. 

I can't find a way reliably connect the `Vec` to the `ListStore` or use it as the data source for the `TreeView`. My naive approach of mapping `vec[n]` to n-th row of the `ListStore` worked only for non-sortable view, but as soon as the view is sorted, `Vec` indices don't correspond to `ListStore` rows any more, so I can't update them (without searching the whole list store for a matching row).

I've tried wrapping my `RustStruct` to be a `GObject` subclass: 

```rust
    let store = ListStore::new(&[RustStructGObjectWrapper::static_type()]);
    tree.set_model(Some(&store)); 

    // creates 3 columns here
```

but it seems like `ListStore` wants 1:1 mapping between number of columns in the `ListStore`:

> 'assertion failed: columns.len() <= n_columns as usize'

I hoped that `TreeViewColumnExt::set_cell_data_func` would let me have one object per row, and copy its properties into separate columns of the `TreeView`, but apparently that's not the way to do it.

----

So it would be helpful for me to see an example of how to go from `struct Model {column1:RefCell<String>, column2:RefCell<String>}; Vec<Model>` to a sortable `TreeView` that displays model's fields, and can update them in the UI when they change.

**Comment by GuillaumeGomez** [comment]
I used sortable trees in process-viewer and bound the sort to "hidden" columns. Here are the lines that might be interesting for you: https://github.com/GuillaumeGomez/process-viewer/blob/master/src/display_procs.rs#L66-L75 and https://github.com/GuillaumeGomez/process-viewer/blob/master/src/display_procs.rs#L177-L180

**Comment by kornelski** [comment]
But this is the thing I'm struggling with: you're storing the data in the `ListStore`. I have my data in a `Vec`.

You're filling the store once, fully, with `insert_with_values`, and don't seem to update later.

**Comment by GuillaumeGomez** [comment]
I actually do here: https://github.com/GuillaumeGomez/process-viewer/blob/15e9252f096f831adda747cb693f0d5c27c1ecab/src/process_viewer.rs#L100-L116

**Comment by kornelski** [comment]
So that's a linear search. It's going to be O(n^2) for me, because in my program I emit an event "7th row of the Vec changed, 3rd row of the Vec changed, 11th row of the Vec changed". If I use an iter to scan through entire model each time to find where my Vec's data ended up in, it'll be super slow.

I have my expectations set by Cocoa, where I can say "`treeview.column1` binds to `mymodel.field1`" and `vec[7].field1.set()` sends a message to `treeview.column1` to update itself.

**Comment by GuillaumeGomez** [comment]
You can try the other way around: using a vec of references to the `liststore`. Then no need to bind data twice.

**Comment by kornelski** [comment]
Does the `TreeIter` survive sorting? i.e. if it was iter of 0th row, and user reverses sorting, is it going to update last row?

**Comment by GuillaumeGomez** [comment]
Good question... I'm pretty sure you can have access to the data location directly, never looked how however. If you find out, please tell me. :3

**Comment by kornelski** [comment]
>  gtk_list_store_set_valuesv: assertion 'iter_is_valid (iter, list_store)' failed

Nope, I can't store iters.

**Comment by kornelski** [comment]
I think I've got a solution:

1. Use an unsorted `ListStore` for 1:1 relationship with `Vec`, and copy data back and forth using index<>row mapping
2. Prevent `ListStore` from being mixed up by wrapping it `TreeModelSort` https://stackoverflow.com/a/19063670/27009
