### ISSUE TITLE
Add Glade signal handlers example if applicable

### ISSUE THREAD

**Issue by adnan449** [gtk-rs/examples#336]
Glade makes it possible to connect to functions to emitted signals. In python they usually create a class called Handler and define methods there. And in Glade the author connects those methods names to appropriate signals: https://python-gtk-3-tutorial.readthedocs.io/en/latest/builder.html#example

Does Gtk-rs offer any such solutions? Thank you.

**Comment by sdroege** [comment]
https://github.com/gtk-rs/examples/blob/5d38aff77331b509f141514e309b8e8cd99cffad/src/bin/builder_signal.rs#L31-L44 is an example of that. It's not very convenient yet, see https://github.com/gtk-rs/gtk-rs/issues/128
