### ISSUE TITLE
Put DEPRECATION notice in README

### ISSUE THREAD

**Issue by nickgerace** [gtk-rs/examples#337]
I was using this repository for a little, and then realzied that it was deprecated in the description. I think it would be great if this was included in the README as well in case folks missed it like I did.

Thank you!

**Comment by GuillaumeGomez** [comment]
Want to send a PR to add it? :)

**Comment by nickgerace** [comment]
Sure thing! Just thought I'd put out an issue first in case there was specific wording you would prefer

**Comment by GuillaumeGomez** [comment]
It can be worked out in the PR if it's not good. Thanks!

**Comment by nickgerace** [comment]
No problem!
