### ISSUE TITLE
Autodetect gtk version

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/examples#59]
Now the user must manually select the version of gtk in the program, at the GTK-rs has autodetection of the current version

**Comment by gkoz** [comment]
It's surprisingly difficult to do cleanly. The `gtk-sys` crate detects the version by invoking `pkg-config`. It passes the knowledge to the `gtk` crate through an [arcane feature](http://doc.crates.io/build-script.html#the-links-manifest-key), which only works for immediate dependencies. So I guess the examples crate would have to depend on `gtk-sys` explicitly and duplicate [this build script](https://github.com/gtk-rs/gtk/blob/master/build.rs).

Additionally I'm not sure it's as useful for the consumer crate to autodetect the version, as it is for the bindings crates.

**Comment by gkoz** [comment]
I'm leaning in the opposite direction: https://github.com/gtk-rs/gtk/issues/243

**Comment by gkoz** [comment]
Now that the crates have version features again, I don't think the examples crate could do anything meaningful in this direction.
