### ISSUE TITLE
[Request] Gtk::Application example

### ISSUE THREAD

**Issue by vaurelios** [gtk-rs/examples#79]
Would be nice have a example of usage `Gtk::Application` in rust, that shows what's recommended way to do this.

**Comment by sdroege** [comment]
Here is a small example https://github.com/chergert/hello/blob/master/rust/src/main.rs

**Comment by sdroege** [comment]
This is not really closed yet, an example in this repository would still be nice to have

**Comment by sdroege** [comment]
Oh well, I filed the more general https://github.com/gtk-rs/examples/issues/140 for this now :)
