### ISSUE TITLE
The procedure entry point inflateReset2 could not be located in the dynamic link library zlib1.dll

### ISSUE THREAD

**Issue by ScottHuangZL** [gtk-rs/examples#95]
I am use Rust 1.11 nightly for windows 7 X64.
I try to build the examples, it can complete successfully, 
however when run the sample exe, it pop up the error dialog with text:

The procedure entry point inflateReset2 could not be located in the dynamic link library zlib1.dll

Could you advise how to resove it? Thanks.

**Comment by ScottHuangZL** [comment]
**The issue tentative resolved by:**
backup C:\Windows\System32\zlib1.dll to zlib1-w32.dll
**copy zlib1.dll from C:\Windows\SysWOW64 to C:\Windows\System32**

Another tentative try, but failed, so have to use above solution.
Copy the zlib1.dll to target\debug folder which same folder as the sample exes,
however, it still not work.

How to let the sample exe to try use the zlib1.dll which in same folder? Thanks.

**Comment by ScottHuangZL** [comment]
I copy the compiled exe to other computer to run, it is win8 x64.
And it pop up error as: "The program can't start because libcairo-2.dll is missing from your computer, Try to reinstalling the program to fix this problem"

And I try to search this dll from my own computer, it seem also not exist. But that exe can run smooth in my computer now.

How to resolve it?

**Comment by GuillaumeGomez** [comment]
cc @gkoz

**Comment by GuillaumeGomez** [comment]
And here, it seems that cairo is missing.

**Comment by gkoz** [comment]
You need to have all the dynamic libraries available on the machine where you run your exe. Either copy them by hand or use some installer, e.g. https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

**Comment by ScottHuangZL** [comment]
Ok, the runtime exe in above link around 50M....
I will try to download for the other machine, thanks.

**Comment by ScottHuangZL** [comment]
It work, please close this issue now, thanks.

**Comment by evandrocoan** [comment]
I just installed this https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases and fixed my problems with GTK on Windows. I also added these value to path:
```
C:\Program Files\GTK3-Runtime Win64\bin
D:\msys64\usr\bin
D:\msys64\mingw64\bin
```
